### ISSUE TITLE
Try run deepstream on Jetson Nano without Docker

### ISSUE THREAD

**Issue by trgkyle** [hiennguyen9874/deepstream-face-recognition#2]
-Em đang thử chạy Deepstream bản 6.0.1 lên Jetson Nano không sử dụng Docker
+ Tuy nhiên em đang setup các bước cài dependencies thì gặp vấn đề ở TensorRT các setup tại https://github.com/hiennguyen9874/deepstream-face-recognition/blob/master/JETSON.md và https://github.com/hiennguyen9874/deepstream-face-recognition/blob/master/Dockerfile.jetson đang pull repo của TensorRT ??? cái này có đúng không ạ, do bản Docker dGPU thì lại pull repo forked của anh
https://github.com/hiennguyen9874/deepstream-face-recognition/blob/master/Dockerfile#L54
cc: @hiennguyen9874

**Comment by trgkyle** [comment]
Vì em cài custom TensorRT qua doc https://github.com/hiennguyen9874/deepstream-face-recognition/blob/master/JETSON.md bị lỗi efficientNMSPlugin
<img width="1064" alt="Screenshot 2022-12-30 at 18 02 20" src="https://user-images.githubusercontent.com/45913828/210063334-3ebe0c89-30e6-4fc7-aeb7-bacb7f15afd1.png">

Còn sửa link repo TensorRT thành repo anh forked thì build engine model bị lỗi

Các bước thực hiện trên Jetson Nano ạ :(

**Comment by hiennguyen9874** [comment]
A mới update lại docs cho jetson. Do mô hình sử dụng custom EfficientNMS plugin không có trong bản TensorRT của nvidia, nên bắt buộc phải sử dụng bản fork của a.

**Comment by trgkyle** [comment]
Vâng anh em thấy anh update doc rồi ạ <3, jetson em dùng là Jetson Nano trong phần build custom TensorRT sửa phần DGPU_ARCHS là 53 thì được rồi ạ
