### ISSUE TITLE
In which path does the face-alignment code work?

### ISSUE THREAD

**Issue by YoungjaeDev** [hiennguyen9874/deepstream-face-recognition#6]
Face-alignment code works on the secondary, but only setting the flag works. Where can I actually see the internal algorithm code?

**Comment by hiennguyen9874** [comment]
INternal algorithm code for face-alignment in [https://github.com/hiennguyen9874/deepstream-face-recognition/blob/8afad7e13740e8425c69a9b867f1cad06857457e/sources/gst-plugins/gst-nvinfer/gstnvinfer.cpp#L1458](https://github.com/hiennguyen9874/deepstream-face-recognition/blob/8afad7e13740e8425c69a9b867f1cad06857457e/sources/gst-plugins/gst-nvinfer/gstnvinfer.cpp#L1458)
